spring.datasource.url=jdbc:postgresql://localhost:5433/authdb_springboot
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

jwt.secret=7c9dbfe2a6e49044b047b6ed1eb5bd8ce473c98171e175cff20f0e2642381f22efddcb4a45233c042e64477069edc0604cf27e08c839df4498d51aabf05dcffe
jwt.expiration=3600000

admin.name=${ADMIN_NAME:Administrador}
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}

frontend.url=${FRONTEND_URL:http://localhost:4200}